### ISSUE TITLE
Self-contained examples

### ISSUE THREAD

**Issue by mguetschow** [cbor-wg/cddl-more-control#2]
I would propose to use self-contained examples, i.e., where all types/groups that are used are also defined (or part of the CDDL prelude).

In particular, the example [in 2.1](https://www.ietf.org/archive/id/draft-ietf-cbor-cddl-more-control-02.html#section-2.1) uses `COSE_Sign1`, and the example [in 2.4](https://www.ietf.org/archive/id/draft-ietf-cbor-cddl-more-control-02.html#section-2.4) uses `issuer` and `expiry`.

Possibly related to #1

**Comment by cabo** [comment]
I think there are competing objectives here:

1.  making an example understandable without context
2.  making an example motivate itself and the feature being demonstrated

Defining all rules might aid (1), or might be counterproductive as the example becomes more complicated.
Reducing the amount of rules that need to be added might remove the motivation that is intrinsic to the existing examples.

On the two examples you cite, I see the balance clearly on the side of keeping the example self-motivating.

**Comment by mguetschow** [comment]
> On the two examples you cite, I see the balance clearly on the side of keeping the example self-motivating.

For the first one, I agree.
For the second one, I don't see a difference if both `issuer` and `expiry` would be replaced by, e.g., `text`.

**Comment by cabo** [comment]
OK, now 9e8c585.
I think we are done with that issue?

**Comment by mguetschow** [comment]
Yes, thank you!
